[book]
title = "go-dims Documentation"
authors = ["Jeremy Collins"]
description = "🚀 Fast, on-the-fly dynamic image management server, written in Go."
language = "en"
multilingual = false
src = "src"
extra-watch-dirs = ["theme"]

[output.html]
additional-css = ["theme/css/custom.css"]
