[book]
title = "Dynamic Image Manipulation Service"
authors = ["Jeremy Collins"]
description = "HTTP microservice for on-the-fly image manipulation written in Go."
language = "en"
multilingual = false
src = "src"
extra-watch-dirs = ["theme"]

[output.html]
additional-css = ["theme/css/custom.css"]
