name: go-dims

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'

jobs:
    docker:
        permissions:
          contents: read
          packages: write

        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Login to Docker Hub (Main)
              uses: docker/login-action@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push (Main)
              uses: docker/build-push-action@v5
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ghcr.io/beetlebugorg/go-dims:edge,beetlebugorg/go-dims:edge

            - name: Build Only (Branches)
              uses: docker/build-push-action@v5
              if: ${{ github.ref != 'refs/heads/main' }}
              with:
                context: .
                push: false
                platforms: linux/amd64