name: go-dims

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'

env:
  RELEASE_TAG: ${{ github.ref_name }}
  TRACKING_TAG: ${{ github.ref == 'refs/heads/main' && 'edge' || 'latest' }}

jobs:
    docker:
        permissions:
          contents: read
          packages: write
          id-token: write

        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::248890141166:role/github-actions-read-ecr
                aws-region: us-east-1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Build and Push (Main)
              uses: docker/build-push-action@v5
              if: ${{ env.RELEASE_TAG == 'main' }}
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }}

            - name: Build and Push (Release)
              uses: docker/build-push-action@v5
              if: ${{ startsWith(env.RELEASE_TAG, 'v') }}
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }},
                      ghcr.io/beetlebugorg/go-dims:${{ env.RELEASE_TAG }}

            - name: Build Only (Branches)
              uses: docker/build-push-action@v5
              if: ${{ env.RELEASE_TAG != 'main' && !startsWith(env.RELEASE_TAG, 'v') }}
              with:
                context: .
                push: false
                platforms: linux/amd64