name: go-dims

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/builder.yml'
      - 'Dockerfile.builder'

env:
  TRACKING_TAG: ${{ github.ref == 'refs/heads/main' && 'edge' || 'latest' }}

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Only (Branches)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64

      - name: Build and Push (Release)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }}-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Only (Branches)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/arm64

      - name: Build and Push (Release)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }}-arm64

  manifest:
    if: github.event_name != 'pull_request'
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute RELEASE_TAG
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "release_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short=8 HEAD)
            echo "release_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }} \
            -t ghcr.io/beetlebugorg/go-dims:${{ steps.tag.outputs.release_tag }} \
            ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG}}-amd64 \
            ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG}}-arm64

  release:
    name: Release
    if: ${{ startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}