name: go-dims

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/build.yml'
    branches:
      - main
  pull_request:

jobs:
    go-dims-docker:
        permissions:
          contents: read
          packages: write

        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: 'Login to GitHub Container Registry'
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Build and Push (Main)
              uses: docker/build-push-action@v5
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ghcr.io/beetlebugorg/go-dims:latest

            - name: Build Only (Branches)
              uses: docker/build-push-action@v5
              if: ${{ github.ref != 'refs/heads/main' }}
              with:
                context: .
                push: false
                platforms: linux/amd64