name: User Guide

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '!.github/workflows/dims.yml'
      - '!.github/workflows/build.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '!.github/workflows/dims.yml'
      - '!.github/workflows/build.yml'

jobs:
  go-dims-docs:
    permissions:
        contents: write
        id-token: write

    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' || 1 }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/book'

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' || 1 }}
        uses: actions/deploy-pages@v4