name: Test deployment

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'docs-pr.yml'
    branches:
      - main

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build