name: Pull Request

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs-pr.yml'
      - '.github/workflows/docs-deploy.yml'
      - '.github/workflows/release.yml'
      - '*.md'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            os: ubuntu-24.04
          - platform: linux/arm64
            os: ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}

      - name: Build Lambda Function
        uses: docker/build-push-action@v5
        id: lambda
        with:
          context: .
          file: Dockerfile.lambda
          push: false
          build-args: VERSION=${{ env.TRACKING_TAG }}
          platforms: ${{ matrix.platform }}
          outputs: type=local,dest=build
