name: Release

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs-pr.yml'
      - '.github/workflows/docs-deploy.yml'
      - '*.md'
    tags:
      - v*

env:
  TRACKING_TAG: ${{ github.ref == 'refs/heads/main' && 'edge' || 'latest' }}

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    name: Build and Push
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            os: ubuntu-24.04
            targetarch: amd64
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            targetarch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v5
        id: container
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.TRACKING_TAG }}
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }}-${{ matrix.targetarch }}

      - name: Build Lambda Function
        uses: docker/build-push-action@v5
        id: lambda
        with:
          context: .
          file: Dockerfile.lambda
          push: false
          build-args: VERSION=${{ env.TRACKING_TAG }}
          platforms: ${{ matrix.platform }}
          outputs: type=local,dest=build

      - name: Upload Lambda zip
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: lambda-linux-${{ matrix.targetarch }}
          path: build/lambda-linux-${{ matrix.targetarch }}.zip

      - name: Build Standalone Binary
        uses: docker/build-push-action@v5
        id: binaries
        with:
          context: .
          file: Dockerfile.binaries
          push: false
          build-args: VERSION=${{ env.TRACKING_TAG }}
          platforms: ${{ matrix.platform }}
          outputs: type=local,dest=build

      - name: Upload Standalone Binary
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: dims-linux-${{ matrix.targetarch }}
          path: build/dims-linux-${{ matrix.targetarch }}.zip

  manifest:
    name: Push Manifest
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute RELEASE_TAG
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # Remove leading 'v' if present
            TAG="${GITHUB_REF_NAME#v}"
            echo "release_tag=${TAG}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short=8 HEAD)
            echo "release_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/beetlebugorg/go-dims:${{ steps.tag.outputs.release_tag }} \
            -t ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG }} \
            ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG}}-amd64 \
            ghcr.io/beetlebugorg/go-dims:${{ env.TRACKING_TAG}}-arm64

  release:
    needs: [build]
    name: Release
    if: ${{ startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: lambda-linux-arm64
          path: ./build

      - uses: actions/download-artifact@v4
        with:
          name: lambda-linux-amd64
          path: ./build

      - uses: actions/download-artifact@v4
        with:
          name: dims-linux-arm64
          path: ./build

      - uses: actions/download-artifact@v4
        with:
          name: dims-linux-amd64
          path: ./build

      - name: Upload to GitHub Release
        run: gh release upload "$TAG_NAME" ./build/lambda-*.zip ./build/dims-*.zip --repo "$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
